matrix:
  include:
    - language: python
      python: 2.7
      script: scripts/lint_python.sh
      cache:
        directories: pip
    - language: node_js
      node_js: 8
      script: scripts/lint_node.sh
      cache:
        directories: node_modules

notifications:
  email: false